spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  auth:
    cookie-secure: true

security:
  clamav:
    enabled: true

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    endpoint: ${S3_ENDPOINT}
    bucket-name: ${S3_BUCKET_NAME}
